language = "English"

[main_menu]
start_opt = '1. Start Game'
leader_opt = '2. Leaderboard'
conf_opt = '3. Configs'
leave_opt = '4. Quit'

input_ask = "\nChoose an option: "

goodbye = 'Goodbye     :('

[leaderboard]
greet = "Leaderboard"

no_score = "You don't have any scores registred :(, try to play some games"
press_continue = "Press Enter to Continue"

[game_over]
greet = "Game Over"
score = "Final Score"
try_again_opt = "Try Again"
save_score_opt = "Save Score"
go_menu_opt = "Go to Main Menu"

input_ask = "\nChoose an option: "

ask_initials = "Enter your initials (3 characters): "
invalid_initials = "Invalid input. Please enter exactly 3 alphabetic characters."
score_sucess = "Your score has been saved successfully!"

wait_msg = "Press Enter to continue"

[game_loop]
giving_up = "You lost by Giving Up :("
eating_tail = "You lost by eating our own tail :("
hitting_wall = "You lost by hitting the wall :("
random_bug = "You lost by a random bug lol"

game_over_greet = "Game Over"

wait_msg = "Press Enter to continue"
score = "Score"
give_up = "Press 'q' any time to give up"

[configs_menu]
greet = "Configs"

difficulty_opt = "1. Change difficulty"
grid_opt = "2. Change game grid size"
lang_opt = "3. Change language"
leader_opt = "4. Clear leaderboard"
leave_opt = "5. Go back"

goback_opt = "Go back"
input_ask = "\nChoose an option: "

greet_difficulty = "Difficulties"
greet_grid = "Grids"
greet_language = "Languages"

leader_conf = "This will delete ALL leaderboard, are you sure?"
leader_yes = "1. Yes"
leader_no = "2. No"
leader_msg = "All leaderboard deleted!"

wait_msg = "Press Enter to continue"

[difficulty]
ign = "IGN"
easy = "Easy"
normal = "Normal"
hard = "Hard"
hell = "HELL"

[grid]
tiny = "TINY"
small = "Small"
medium = "Medium"
big = "Big"
huge = "HUGE"

[languages]
en = "English"
br = "Brazilian Portuguese"
